### ISSUE TITLE
Feature request: exclude specific dependencies

### ISSUE THREAD

**Issue by madsop** [AyoyAB/Ayoy-Maven-License-Verifier-Plugin#1]
In my project, we have some dependencies that we know are missing licenses, but we can handle them manually. Hence, we want to exclude those from the check.

**Comment by smuda** [comment]
Could you give me an example and what the plugin currently does?

**Comment by madsop** [comment]
Sure.
Currently, this is the part from our pom-file:
`<plugin>
                    <groupId>se.ayoy.maven-plugins</groupId>
                    <artifactId>ayoy-license-verifier-maven-plugin</artifactId>
                    <version>1.0.1</version>
                    <executions>
                        <execution>
                            <phase>compile</phase>
                            <goals>
                                <goal>verify</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <licenseFile>${licenseFilePath}</licenseFile>
                        <failOnForbidden>true</failOnForbidden>
                        <failOnMissing>false</failOnMissing>
                        <failOnUnknown>true</failOnUnknown>
                    </configuration>
                </plugin>`

An example:
[INFO] --- ayoy-license-verifier-maven-plugin:1.0.1:verify (default-cli) @ servertests ---
[INFO] Parsing dependencies.
[INFO] Found 65 artifacts. Now validating their licenses with the list.
[WARNING] MISSING   artifact com.oracle.weblogic:wlthint3client:jar:12.2.1-2-1:compile

Hence, we have set the failOnMissing property to false. However, we ideally want to enable failOnMissing, to ensure we are not accidentaly introducing new dependencies without defined licenses.

**Comment by smuda** [comment]
Thank you!
I've added a possibility to exclude known artefacts without licenses by adding a new parameter called `excludedMissingLicensesFile`.

You should be able to use it like this:

```
<plugin>
    <groupId>se.ayoy.maven-plugins</groupId>
    <artifactId>ayoy-license-verifier-maven-plugin</artifactId>
    <version>1.0.1-SNAPSHOT</version>
    <executions>
        <execution>
            <phase>compile</phase>
            <goals>
                <goal>verify</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <licenseFile>${project.parent.basedir}/licenses/licenses.xml</licenseFile>
        <excludedMissingLicensesFile>${project.parent.basedir}/licenses/allowedMissingLicense.xml</excludedMissingLicensesFile>
        <failOnForbidden>true</failOnForbidden>
        <failOnMissing>true</failOnMissing>
        <failOnUnknown>true</failOnUnknown>
    </configuration>
</plugin>
```

The content of the file looks like this:
```
<?xml version="1.0"?>
<missing>
    <dependency>
        <groupId>com.oracle.weblogic</groupId>
        <artifactId>wlthint3client</artifactId>
        <version>12.2.1-2-1</version>
    </dependency>
</missing>
```
Would you be able to compile and install the plugin to try it out before I release and publish?

**Comment by madsop** [comment]
Thanks! I just tried it locally, and it works fine.

**Comment by smuda** [comment]
Lovely! I'll release and publish tonight.

**Comment by smuda** [comment]
I'm having problems with the release process. 

The artifacts are published to oss.sonatype.org but for some reason the don't seem to be sync'ed to [https://mvnrepository.com/artifact/se.ayoy.maven-plugins/ayoy-license-verifier-maven-plugin](https://mvnrepository.com/artifact/se.ayoy.maven-plugins/ayoy-license-verifier-maven-plugin).

**Comment by smuda** [comment]
As far as I can see v1.0.3 is published OK now.
@madsop Will you close issue after verification?

**Comment by madsop** [comment]
Just verified that this is all good. Thanks!

**Comment by sebastien-dev-roy** [comment]
Hi,

I know that this feature is closed and should be working, but I've spent a couple of hours trying to make it work. I always end up with the same error in my build 


```
[WARNING] UNKNOWN   artifact org.hibernate.javax.persistence:hibernate-jpa-2.0-api:jar:1.0.1.Final:compile with licenses: "null"
[WARNING]           license:  name: (null), names: [(null)], urls: ["license.txt"]
[WARNING]           dependency chain: pom -> org.hibernate:hibernate-core -> org.hibernate.javax.persistence:hibernate-jpa-2.0-api
```

But I think that I've done the right thing in my **allowedMissingLicense.xml** but not seem to be able to properly ignore the dependency:

```
<?xml version="1.0"?>
<missing>
	<dependency>
	    <groupId>org.hibernate.javax.persistence</groupId>
	    <artifactId>hibernate-jpa-2.0-api</artifactId>
	    <version>1.0.1.Final</version>
	</dependency>
	<dependency>
	    <groupId>org.hibernate</groupId>
	    <artifactId>hibernate-core</artifactId>
	    <version>3.6.10.Final</version>
	</dependency>	
</missing>
```

I will next take a look at the code. I'm not just sure how easy it is to setup myself to test a Maven plugin.

Regards,

**Comment by smuda** [comment]
@sebastien-dev-roy It seems your issue is related but not quite the same as this issue. I've created issue #6 where we can continue.
