### ISSUE TITLE
Support for dual licenses

### ISSUE THREAD

**Issue by madsop** [AyoyAB/Ayoy-Maven-License-Verifier-Plugin#13]
Some libraries are published with a dual license, for instance CDDL+GPL. An [explanation ](https://netbeans.org/about/legal/license-change.html)is available at NetBeans

Libraries such as `[Streaming API For XML](https://mvnrepository.com/artifact/javax.xml.stream/stax-api/1.0-2)` is dual licensed, and list both licenses in a list, as this: "GNU General Public Library", "COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (CDDL) Version 1.0"

I have GPL in my forbidden list, and CDDL among my allowed licenses. This now fails with forbidden, I'd expect it to pass OK.

_[WARNING] FORBIDDEN artifact javax.xml.stream:stax-api:jar:1.0-2:provided with licenses: "GNU General Public Library", "COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (CDDL) Version 1.0"
[WARNING]           license:  name: "GNU General Public License", names: ["GNU General Public License version 2", "GNU General Public Library"], urls: ["https://opensource.org/licenses/gpl-2.0.php", "http://www.gnu.org/licenses/gpl.txt"]
[WARNING]           dependency chain: pom -> javax:javaee-api -> javax.xml.stream:stax-api_

**Comment by madsop** [comment]
Ok, I now see the test _bothInvalidAndValidLicense1_, so this is perhaps a deliberate choice?

If so, how about a property or so to adjust how this should behave?

**Comment by smuda** [comment]
There is a property called `requireAllValid` which you set to false which should handle your use-case.

Thats reflected in the unit test `bothInvalidAndValidLicense2`.

I've also added two integration tests to validate the behavior; `artifact-with-dual-license-and-allowed` and `artifact-with-dual-license-and-forbidden`.

**Comment by madsop** [comment]
Great! How about adding a _configuration_ section to the readme, so that others don't overlook it as I did?

**Comment by smuda** [comment]
@madsop Totally agree! Would you be able to create a PR for that?

**Comment by madsop** [comment]
@smuda: Yes, I'll give it a try. Would be interesting to see if I've understood the config properties correct 😃

**Comment by smuda** [comment]
@madsop I have the utmost confidence in you! 😃
