### ISSUE TITLE
Parameter to only check direct dependencies

### ISSUE THREAD

**Issue by madsop** [AyoyAB/Ayoy-Maven-License-Verifier-Plugin#14]
Sometimes (probably usually), you want to check for transitive dependencies as well.

However, sometimes, you are only interested in checking your direct dependencies. It should be possible to only check the direct dependencies, for instance through a property.

**Comment by madsop** [comment]
I'll create a pull request on this one.

**Comment by madsop** [comment]
An example: We have a dependency on Oracle WebLogic in our system. That dependency in turn depends on ~100 transitive dependencies without license defined.

**Comment by madsop** [comment]
Another solution here might be to allow exclusion of specific dependencies from analysis. Quite similar to the allowedMissingLicenses functionality that is today.

**Comment by smuda** [comment]
@madsop 
I like your idea to use something the allowedMissingLicenses. Perhaps even a parameter in allowedMissingLicenses to exclude transitive dependencies would be a nice solution? 

Something like this:

```XML
    <dependency>
        <groupId>org.hibernate.javax.persistence</groupId>
        <artifactId>hibernate-jpa-2.0-api</artifactId>
        <version>1.0.1.Final</version>
        <checkDependencies>false</checkDependencies>
    </dependency>
```
where the default value of checkDependencies is true. That gives the flexibility to selectively disable checking transient dependencies on only one dependency.

**Comment by smuda** [comment]
In LicenseAbstractMojo.java, function resolveArtifacts starts like this:
```
    private ArrayList<AyoyArtifact> resolveArtifacts(
            Set<Artifact> artifacts,
            ProjectBuildingRequest buildingRequest,
            ExcludedMissingLicenseFile excludedArtifacts,
            AyoyArtifact parent) {

        ArrayList<AyoyArtifact> toReturn = new ArrayList<>();
        for (Artifact artifact: artifacts) {
            if (!shouldArtifactBeIncluded(artifact, excludedArtifacts)) {
                continue;
            }
...
```

Therefor, if you add the dependency which you don't want to check for transitive dependencies to allowedMissingLicenses, it wouldn't check that. Could you please verify?

**Comment by madsop** [comment]
I just tried the workaround (which I think it is to add the dependency to allowedMissingLicenses, and indeed, it works ass intended. That's useful to know.

**Comment by madsop** [comment]
Also discovered today that time is a factor: For our legacy system, each maven-module brings in a lot (true, way too many) of transitive dependencies (several thousands). That makes the analysis slow. So at least for that use case it's a need to be able to disable transitive analysis in general.

**Comment by smuda** [comment]
There is a lot at work currently so it will take a few days for me to look more into this.

Out of curiosity, what kind of timeframes are talking about when running in your legacy system? 1 minute? 10 minutes? 30 minutes?

**Comment by smuda** [comment]
@madsop Sorry for the long delay. I've now merged your pull request.

Out of curiosity, what kind of timeframes are talking about when running in your legacy system? 1 minute? 10 minutes? 30 minutes?

**Comment by madsop** [comment]
Thanks! No need to apologize, that's how maintaining in your free time is.

I haven't timed it, but just stopped a build after ~15 minutes - finished 1/10th of the modules. The usual build time is 10 minutes (yes, I know...) for the entire project.

When running on just one module with -X, it seems that the same dependencies are evaluated over and over again. So perhaps an optimization might be to keep track of already evaluated dependencies?

**Comment by smuda** [comment]
@madsop Yeah, I suppose that if multiple dependencies use the same dependencies, that will happen. I'll open up a separate task for that. Will you help me with an integration test?

**Comment by smuda** [comment]
@madsop If this issue is verified as resolved, will you please close the issue?
