### ISSUE TITLE
Low performance due to the same dependency being parsed multiple times

### ISSUE THREAD

**Issue by smuda** [AyoyAB/Ayoy-Maven-License-Verifier-Plugin#17]
From @madsop in #14:

> I haven't timed it, but just stopped a build after ~15 minutes - finished 1/10th of the modules. The usual build time is 10 minutes (yes, I know...) for the entire project.
> 
> When running on just one module with -X, it seems that the same dependencies are evaluated over and over again. So perhaps an optimization might be to keep track of already evaluated dependencies?

**Comment by madsop** [comment]
I'll create a test to verify this problem.

**Comment by smuda** [comment]
@madsop Have a look at bransch issue17. Would that solve your problem?

**Comment by madsop** [comment]
@smuda : I think so, it looks very promising!

**Comment by madsop** [comment]
@smuda: Would you be able to merge this and push a new version to Maven central? I think this and the other recent enhancements will enable us to use the plugin again.

**Comment by smuda** [comment]
@madsop Sure! I've release now but Sonatype tends to take a couple of days before it ends up in maven central.

Will you close this issue now?

**Comment by madsop** [comment]
Great, thanks! Doesn't look like I have the possibility to close an issue?
