### ISSUE TITLE
Centralized license.xml

### ISSUE THREAD

**Issue by madsop** [AyoyAB/Ayoy-Maven-License-Verifier-Plugin#23]
We have a project with an emerging microservice architecture, so currently, we've duplicated the licenses.xml file to every application's repository.

It would be much easier to deal with having to update only one file across all these applications.

Guess there are several ways to do this, for instance by providing a URL to the file. Perhaps this works out of the box already? If so, I guess we should clarify it in the documentation.

**Comment by madsop** [comment]
I realize now that #9 probably could be a feasible solution to this problem as well.

**Comment by smuda** [comment]
PR #21 has been merged. Check out if the result matches your request.

**Comment by madsop-nav** [comment]
Finally got the chance to try out the functionality from #21 , and yes, it solves my problem as well.

So I'd be happy if you could release 1.1.1 whenever suitable 😃

**Comment by madsop-nav** [comment]
Hi, @smuda. We're eager to start using 1.1.1 now, so it'd be great if you could release it.

**Comment by smuda** [comment]
@computas-mop @madsop I've released 1.2.0 now but it usually takes several days before it ends up in maven central.

I'll close this issue and if I'm in error, please re-open.
