### ISSUE TITLE
The plugin should verify transitive dependencies

### ISSUE THREAD

**Issue by Tibor17** [AyoyAB/Ayoy-Maven-License-Verifier-Plugin#3]
According to my experiences the plugin verifies direct dependencies.
Pls support transitive dependencies as well.

**Comment by Tibor17** [comment]
@smuda I think I may provide you with a hint.
Continue in [the loop](https://github.com/AyoyAB/Ayoy-Maven-License-Verifier-Plugin/blob/master/src/main/java/se/ayoy/maven/plugins/licenseverifier/LicenseAbstractMojo.java#L70) then take the `artifact` and resolve it to [transitive dependencies](https://github.com/apache/maven-surefire/blob/master/maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/SurefireDependencyResolver.java#L127).

**Comment by smuda** [comment]
@Tibor17 
I'm a bit short on time at the moment, would you be able to provide a pull request?

Please take care to include logging to show "the path" to the unwanted license.

**Comment by Tibor17** [comment]
I will start working on it in the weekend.

**Comment by smuda** [comment]
@Tibor17 Lovely, thank you!

**Comment by smuda** [comment]
@Tibor17 
Now that I've merged the PR, I'm prepared to do a new release.
Unless there is anything more you've noted?

**Comment by Tibor17** [comment]
Feel free to make the release. The cosmetic changes with `requireNonNull` can be done always.

**Comment by Tibor17** [comment]
Closing as #4 has been merged in master.
