### ISSUE TITLE
Unclassified licenses

### ISSUE THREAD

**Issue by dariobraun** [AyoyAB/Ayoy-Maven-License-Verifier-Plugin#7]
The plugin does not seem to recognize certain licenses: 

"One or more artifacts has licenses which is unclassified"

I tried checking lombok and junit.

**Comment by smuda** [comment]
@dariobraun It's up to you to classify each license. Have you included a license classification file?

**Comment by dariobraun** [comment]
@smuda Yeah, thank you! I think I misinterpreted the error message - my bad!
